name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  # specifying a specific python version to avoid deprecation errors
  - python==3.8
  - cookiecutter
  - hydra-core
  - git
  - ipython
  - notebook
  - jupyterlab
  - pip
  - pip:
      - wandb
      - mlflow
      - matplotlib
      - pandas

# removing the versions to avoid errors due to deprecated packages
# https://knowledge.udacity.com/questions/993110
