FROM continuumio/miniconda3

WORKDIR /project

# Install system packages if needed
RUN apt-get update && apt-get install -yq curl wget jq vim

# Install Miniconda or Anaconda
RUN curl -LO "http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh"
RUN bash Miniconda3-latest-Linux-x86_64.sh -p /miniconda -b
RUN rm Miniconda3-latest-Linux-x86_64.sh
ENV PATH=/miniconda/bin:${PATH}

# The last version released with a python3.6 variant was version 5.2.0
# https://stackoverflow.com/questions/54801513/how-can-i-download-anaconda-for-python-3-6
# RUN curl -LO "https://repo.anaconda.com/archive/Anaconda3-5.2.0-Linux-x86_64.sh"
# installing in silent mode
# https://docs.anaconda.com/free/anaconda/install/silent-mode/#linux-macos
# RUN bash Anaconda3-5.2.0-Linux-x86_64.sh -p /anaconda -b
# RUN rm Anaconda3-5.2.0-Linux-x86_64.sh
# ENV PATH=/anaconda/bin:${PATH}

# Update Conda and activate the environment
# RUN conda update -y conda
# RUN conda init bash

# use bash as a shell (to avoid the "/bin/sh: 1: source: not found" error)
# https://stackoverflow.com/questions/20635472/using-the-run-instruction-in-a-dockerfile-with-source-does-not-work
# SHELL ["/bin/bash", "-c"]
# RUN source /root/.bashrc
# to make the conda activate command work
# RUN source /anaconda/bin/activate

# COPY . .

# as recommended in this stackoverflow thread, use mamba as a better replacement for conda!
# https://stackoverflow.com/questions/63734508/stuck-at-solving-environment-on-anaconda
# RUN conda install -n base conda-forge::mamba -y
# RUN conda install -n base --override-channels -c conda-forge mamba 'python_abi=*=*cp*' -y

# RUN conda install -c anaconda -y python=3.6
# RUN conda install python=3.6.0
# RUN bash create_env.sh

# this didn't work! since we're in a docker container, let's install directly in the base environment
# RUN conda create --name nyc_airbnb_dev
# RUN conda activate nyc_airbnb_dev

# I get a PackagesNotFoundError when I try to install the specific version in environment.yml, this is why I have to install everything manually!
# https://anaconda.org/conda-forge/mlflow
RUN conda install mlflow -y
RUN conda install ipython -y
RUN conda install notebook -y
RUN conda install jupyterlab -y
RUN conda install cookiecutter -y
# https://anaconda.org/conda-forge/hydra-core
RUN conda install -c conda-forge hydra-core
RUN conda install matplotlib -y
RUN conda install pandas -y
RUN conda install git -y
RUN conda install pip
RUN pip install wandb

COPY . .

CMD [ "bash" ]
